### ISSUE TITLE
Running protractor tests with --grep="test", creates xml report of non executed tests

### ISSUE THREAD

**Issue by rohitkadam19** [larrymyers/jasmine-reporters#118]
Run protractor tests with --grep="test" option.

It will run test with grep option but xml report will have all other tests as well.
And on console it will show other tests as Pending.

**Comment by bloveridge** [comment]
Running jasmine with `--grep` is equivalent to using `fit` / `fdescribe` to selectively enable certain tests. Jasmine makes not distinction in the call to the reporter between specs / suites that were disabled via `xit` / `xdescribe` and ones that were excluded because of the use of `grep` / `fit` / `fdescribe`. jasmine-reporters currently has no option to exclude disabled / skipped specs from XML output.

If this functionality is important to you, please consider creating a PR that adds this functionality via a new option to `JUnitXmlReporter` (e.g. `suppressDisabledSpecs: true`), but there are no plans to make this the default behavior—it is often important to see any specs that are pending / disabled, and so the default behavior needs to be as inclusive as possible.
