### ISSUE TITLE
Include specfile filename in XML output

### ISSUE THREAD

**Issue by jas13** [larrymyers/jasmine-reporters#121]
Does anyone have any ideas on how to do this?

**Comment by bloveridge** [comment]
Can you be a bit more specific with your request? I'm not sure what you are trying to accomplish. 

If you set consolidateAll=true, whatever you provide for filePrefix becomes the file name. For example, `consolidateAll: true, filePrefix: "myTestResults"` will result in your output file being called myTestResults.xml

**Comment by jas13** [comment]
Currently the output files are generated per spec file, but are named by the description in the top-level `describe` block. Suppose a spec file `login_tests.js` has a top-level `describe` description of `The Login Page`. The resulting output file would be named `TEST-TheLoginPage.xml`. But nowhere in the content on the file is the filename of the spec file `login_tests`. It is that file name which I need to be included in the output file.

**Comment by bloveridge** [comment]
@jas13 Did you figure out a workable solution for this? I do not believe the JUnit XML schema has a specific place where information like this should go, but as it's XML something could probably be shoe-horned in if necessary. Also, additional options have recently been added which may help to address your issue.

As this seems like a non-critical enhancement request without much activity in the last 8 months, I'm closing this issue. Please feel free to open a pull request if this issue is still causing you grief and you have a specific idea for how it can be solved cleanly.

**Comment by jas13** [comment]
@bloveridge I devised a workaround. Basically before the specs are run on the CI environment being used, a script is run on every specfile that wraps the whole file in a top-level `describe`-block that includes the filename. So a file named `login_tests.js` would have a top-level `describe` inserted with text 'login_tests`. That way the name of the output file corresponds to the input file.
