### ISSUE TITLE
usage of TeamcityReporter with Protractor

### ISSUE THREAD

**Issue by liadlivnat** [larrymyers/jasmine-reporters#75]
Hi,
I'm wondering how should i configure the team city reporter.
the output shown in the console log but not in the output directory.

i would like the files to be saved to a certain directory, here is what i did:

```
	  onPrepare: function() {
		// The require statement must be down here, since jasmine-reporters@1.0
		// needs jasmine to be in the global and protractor does not guarantee
		// this until inside the onPrepare function.
		require('jasmine-reporters');
		jasmine.getEnv().addReporter(
			new jasmine.TeamcityReporter('xmloutput', true, true)
		);
	},
```

Can someone tell me what am i doing wrong?

**Comment by bloveridge** [comment]
I'm not intimately familiar with TeamCity, but my understanding of how it works is by reading data from the console / stdout. Is there a mechanism whereby TeamCity can read the results from a file rather than stdout?

Writing TeamCity logs to a file has never been implemented; the example you provided is using arguments for the JUnitReporter, none of which mean anything for the TeamCity reporter, which accepts no arguments at this time.

If TeamCity supports reading results from a file, the TeamCityReporter could certainly be expanded to optionally write the log messages to a file.

Is that what you are asking for?

**Comment by liadlivnat** [comment]
Yes i was basically asking you to help me understand how this mechanism work, the reporter is working i can see the output in the console, and maybe there is a way that team city will read it from the stdout, not sure about it,also i will remove the argument from the reporter. thanks!
