### ISSUE TITLE
Can't find variable: __phantom_writeFile

### ISSUE THREAD

**Issue by sayakb** [larrymyers/jasmine-reporters#79]
First of all, thank you for the awesome plugins!

I did find a couple of posts here and there on this issue, but since I am stuck with jasmine 1.3.1 (due to extensive usage of lazy loading in my angular.js application wherein jasmine 2.0 doesn't play nice), upgrading jasmine isn't possible unfortunately.

I am invoking the tests from phantomjs:

```
page.open('http://localhost:31531/tests/', function () {
    var monitor = setInterval(function () {
        // Capture the document element of the page
        var doc = page.evaluate(function () {
            return document;
        });

        // Execution completed
        if (doc.jasmineCompleted) {
            clearInterval(monitor);
            phantom.exit(returnCode);
        }
    }, 10);
});
```

And this is how I initialize my reporters:

```
var jasmineEnv = jasmine.getEnv();
var callback = jasmineEnv.currentRunner().finishCallback;

jasmineEnv.updateInterval = 1000;
jasmineEnv.addReporter(new jasmine.HtmlReporter());
jasmineEnv.addReporter(new jasmine.TapReporter());
jasmineEnv.addReporter(new jasmine.JUnitXmlReporter('.'));

jasmineEnv.currentRunner().finishCallback = function () {
    callback.call(this);
    document.jasmineCompleted = true;
};

jasmineEnv.execute();
```

The HTML and tap reporters work just fine. However the JUnit reporter throws this message:

```
Warning: writing junit report failed for 'C:\My\Projects\HudsonCI\TestScripts', 'TEST-layoutControllerTest.xml'. Reasons:
  Rhino attempt: Can't find variable: java
  PhantomJs attempt: Can't find variable: __phantom_writeFile
  NodeJS attempt: Module name "fs" has not been loaded yet for context: _. Use require([])
http://requirejs.org/docs/errors.html#notloaded
```

While I understand that jasmine 1.x may not be fully supported, is there anything I can do to get this working on my end? My tests are being run on a windows 7 Hudson build slave.

**Comment by bloveridge** [comment]
The problem is that your PhantomJS environment doesn't provide all the things expected by `JUnitXmlReporter`. The easiest (and supported) way to use this reporter with PhantomJS is using the included `phantomjs-testrunner.js` file, which sets up the environment for JUnitXmlReporter including the global `__phantom_writeFile` function used to write the document to file. I recommend looking into using this runner if at all possible.

If you can't use the provided file directly, you might be able to pick parts of it into your own phantomjs script to make it work. Here's the general gist of what you'd need to do:

1. When the Jasmine page is initialized, inject a function `window.__phantom_writeFile`. This function will be called with two arguments: the filename and the xml text.
2. Store this data in some variable / map / etc (we store it in a simple key:value map)
3. When the reporters are finished, grab the filenames and xml data. Write it using PhantomJS and bail.

This runaround is necessary because the actual webpage you are loading (Jasmine tests) can't access the outside PhantomJS environment directly. Instead, the PhantomJS environment has to reach in. So it reaches in to make a function that stores data where the PhantomJS knows to look for it, and then it reaches in when everything is done to grab that data and write it.

Good luck.

**Comment by sayakb** [comment]
Thank you, that is something that I can certainly do. You have a good weekend!
