### ISSUE TITLE
Jasmine-reporters 2 is not in npm

### ISSUE THREAD

**Issue by 0xR** [larrymyers/jasmine-reporters#81]
I can't figure out why jasmine-reporters2 is not in npm. On npm it is still on 1.0.1. If I want to use this package properly I need it to be on npm.

https://www.npmjs.com/package/jasmine-reporters

**Comment by bloveridge** [comment]
2.x is, and always has been, on npm. However, because both a 1.x and 2.x branch are maintained within the same `jasmine-reporters` npm package, npmjs.com shows the latest published release as the "latest"  and that is also what gets used if you just say `npm install jasmine-reporters`. A patch on the 1.x branch was made recently, so it was published to npm and became the "latest" version. I just published a couple minor changes to the 2.x branch so `2.0.4` now appears as the latest on npm.

You can always view the complete list of available versions by running `npm info jasmine-reporters`, and you can install a specific version by running `npm install jasmine-reporters@2.0.4`, etc.
